services:
  chara:
    image: ghcr.io/yousafe/chara:latest
    ports:
      - "3000:3000"
    environment:
      - DB_URL=ws://surrealdb:8000
      - DB_USERNAME=yousafe
      - DB_PASSWORD=MRAOWR
      - BIT_PATH=/bit
      - MASTER_KEY=${MASTER_KEY}
      - REDIRECT_URI=${REDIRECT_URI}
      - CLIENT_ID=${CLIENT_ID:-}
      - CLIENT_SECRET=${CLIENT_SECRET:-}
      - RUST_LOG=info
    volumes:
      - ./bit:/bit
    depends_on:
      - surrealdb

  surrealdb:
    image: surrealdb/surrealdb:v2.1.4
    command: >
      start
      --user yousafe
      --pass MRAOWR
      --bind 0.0.0.0:8000
      --allow-all
      mem
    environment:
      - SURREAL_BUCKET_FOLDER_ALLOWLIST=/bit
    volumes:
      - ./bit:/bit
    ports:
      - "8000:8000"
