target = "rust"
abi = 2

[package]
organisation = "chaira"
name = "charli"
version = "0.0.1"

[capabilities]
allow_scripting = false
allow_arbitrary_queries = false
allow_functions = ["charli::*"]
allow_net = []
strict_timeout = true

[attach]
