name: Formating and Checking 

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Check & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: https://github.com/actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo check
        run: cargo check --all-features

      - name: Install leptosfmt
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install.sh | sh
          cargo binstall leptosfmt -y

      - name: Check formatting with leptosfmt
        run: leptosfmt --check .
