[package]
name = "models"
version = "0.0.1"
edition = "2024"

[dependencies]
bitmask = "0.5.0"
iso_currency = { version = "0.5.3", features = ["with-serde"] }
mime = "0.3.17"
ordered-float = { version = "5.3.0", features = ["serde"] }
phonenumber = "0.3.9"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
validator.workspace = true
surrealdb.workspace = true
chrono.workspace = true
